# Config file .travis.yml

language: python

python:
#  - "pypy" # not supported by odoo 8
#  - "3.4"  # not supported by odoo 8
#  - "3.3"  # not supported by odoo 8
  - "2.7"
#  - "2.6"  # not supported by odoo 8

env:
  global:
  - VERSION="8.0" ODOO_REPO="odoo/odoo" UNIT_TEST="0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="0"
  - TESTS="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
