# Config file .travis.yml

language: python

python:
  - "2.7"

addons:
  apt:
    packages:
      - python-lxml  # because pip installation is slow

env:
  global:
  - VERSION="8.0" ODOO_REPO="odoo/odoo" UNIT_TEST="0" TESTS="0" LINT_CHECK="0"

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="0"
  - TESTS="1" ODOO_REPO="odoo/odoo"

virtualenv:
  system_site_packages: true

install:
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
